// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: map_proto.proto

package ignfab.minetest;

public final class MapProto {
  private MapProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MapOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Map)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 chunk_blocks = 1;</code>
     */
    boolean hasChunkBlocks();
    /**
     * <code>required int32 chunk_blocks = 1;</code>
     */
    int getChunkBlocks();

    /**
     * <code>repeated .Map.Block blocks = 2;</code>
     */
    java.util.List<ignfab.minetest.MapProto.Map.Block> 
        getBlocksList();
    /**
     * <code>repeated .Map.Block blocks = 2;</code>
     */
    ignfab.minetest.MapProto.Map.Block getBlocks(int index);
    /**
     * <code>repeated .Map.Block blocks = 2;</code>
     */
    int getBlocksCount();
    /**
     * <code>repeated .Map.Block blocks = 2;</code>
     */
    java.util.List<? extends ignfab.minetest.MapProto.Map.BlockOrBuilder> 
        getBlocksOrBuilderList();
    /**
     * <code>repeated .Map.Block blocks = 2;</code>
     */
    ignfab.minetest.MapProto.Map.BlockOrBuilder getBlocksOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Map}
   */
  public  static final class Map extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Map)
      MapOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Map.newBuilder() to construct.
    private Map(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Map() {
      chunkBlocks_ = 0;
      blocks_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Map(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              chunkBlocks_ = input.readInt32();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                blocks_ = new java.util.ArrayList<ignfab.minetest.MapProto.Map.Block>();
                mutable_bitField0_ |= 0x00000002;
              }
              blocks_.add(
                  input.readMessage(ignfab.minetest.MapProto.Map.Block.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          blocks_ = java.util.Collections.unmodifiableList(blocks_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ignfab.minetest.MapProto.internal_static_Map_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ignfab.minetest.MapProto.internal_static_Map_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ignfab.minetest.MapProto.Map.class, ignfab.minetest.MapProto.Map.Builder.class);
    }

    public interface BlockOrBuilder extends
        // @@protoc_insertion_point(interface_extends:Map.Block)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required int32 x = 1;</code>
       */
      boolean hasX();
      /**
       * <code>required int32 x = 1;</code>
       */
      int getX();

      /**
       * <code>required int32 y = 2;</code>
       */
      boolean hasY();
      /**
       * <code>required int32 y = 2;</code>
       */
      int getY();

      /**
       * <code>required int32 z = 3;</code>
       */
      boolean hasZ();
      /**
       * <code>required int32 z = 3;</code>
       */
      int getZ();

      /**
       * <code>required string type = 4;</code>
       */
      boolean hasType();
      /**
       * <code>required string type = 4;</code>
       */
      java.lang.String getType();
      /**
       * <code>required string type = 4;</code>
       */
      com.google.protobuf.ByteString
          getTypeBytes();
    }
    /**
     * Protobuf type {@code Map.Block}
     */
    public  static final class Block extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:Map.Block)
        BlockOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Block.newBuilder() to construct.
      private Block(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Block() {
        x_ = 0;
        y_ = 0;
        z_ = 0;
        type_ = "";
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Block(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                x_ = input.readInt32();
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                y_ = input.readInt32();
                break;
              }
              case 24: {
                bitField0_ |= 0x00000004;
                z_ = input.readInt32();
                break;
              }
              case 34: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000008;
                type_ = bs;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ignfab.minetest.MapProto.internal_static_Map_Block_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ignfab.minetest.MapProto.internal_static_Map_Block_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ignfab.minetest.MapProto.Map.Block.class, ignfab.minetest.MapProto.Map.Block.Builder.class);
      }

      private int bitField0_;
      public static final int X_FIELD_NUMBER = 1;
      private int x_;
      /**
       * <code>required int32 x = 1;</code>
       */
      public boolean hasX() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 x = 1;</code>
       */
      public int getX() {
        return x_;
      }

      public static final int Y_FIELD_NUMBER = 2;
      private int y_;
      /**
       * <code>required int32 y = 2;</code>
       */
      public boolean hasY() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 y = 2;</code>
       */
      public int getY() {
        return y_;
      }

      public static final int Z_FIELD_NUMBER = 3;
      private int z_;
      /**
       * <code>required int32 z = 3;</code>
       */
      public boolean hasZ() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 z = 3;</code>
       */
      public int getZ() {
        return z_;
      }

      public static final int TYPE_FIELD_NUMBER = 4;
      private volatile java.lang.Object type_;
      /**
       * <code>required string type = 4;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string type = 4;</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            type_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string type = 4;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasX()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasY()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasZ()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasType()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, x_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeInt32(2, y_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeInt32(3, z_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 4, type_);
        }
        unknownFields.writeTo(output);
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, x_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, y_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(3, z_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, type_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof ignfab.minetest.MapProto.Map.Block)) {
          return super.equals(obj);
        }
        ignfab.minetest.MapProto.Map.Block other = (ignfab.minetest.MapProto.Map.Block) obj;

        boolean result = true;
        result = result && (hasX() == other.hasX());
        if (hasX()) {
          result = result && (getX()
              == other.getX());
        }
        result = result && (hasY() == other.hasY());
        if (hasY()) {
          result = result && (getY()
              == other.getY());
        }
        result = result && (hasZ() == other.hasZ());
        if (hasZ()) {
          result = result && (getZ()
              == other.getZ());
        }
        result = result && (hasType() == other.hasType());
        if (hasType()) {
          result = result && getType()
              .equals(other.getType());
        }
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasX()) {
          hash = (37 * hash) + X_FIELD_NUMBER;
          hash = (53 * hash) + getX();
        }
        if (hasY()) {
          hash = (37 * hash) + Y_FIELD_NUMBER;
          hash = (53 * hash) + getY();
        }
        if (hasZ()) {
          hash = (37 * hash) + Z_FIELD_NUMBER;
          hash = (53 * hash) + getZ();
        }
        if (hasType()) {
          hash = (37 * hash) + TYPE_FIELD_NUMBER;
          hash = (53 * hash) + getType().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static ignfab.minetest.MapProto.Map.Block parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static ignfab.minetest.MapProto.Map.Block parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static ignfab.minetest.MapProto.Map.Block parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static ignfab.minetest.MapProto.Map.Block parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static ignfab.minetest.MapProto.Map.Block parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static ignfab.minetest.MapProto.Map.Block parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static ignfab.minetest.MapProto.Map.Block parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static ignfab.minetest.MapProto.Map.Block parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static ignfab.minetest.MapProto.Map.Block parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static ignfab.minetest.MapProto.Map.Block parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static ignfab.minetest.MapProto.Map.Block parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static ignfab.minetest.MapProto.Map.Block parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(ignfab.minetest.MapProto.Map.Block prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code Map.Block}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:Map.Block)
          ignfab.minetest.MapProto.Map.BlockOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return ignfab.minetest.MapProto.internal_static_Map_Block_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return ignfab.minetest.MapProto.internal_static_Map_Block_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  ignfab.minetest.MapProto.Map.Block.class, ignfab.minetest.MapProto.Map.Block.Builder.class);
        }

        // Construct using ignfab.minetest.MapProto.Map.Block.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          x_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          y_ = 0;
          bitField0_ = (bitField0_ & ~0x00000002);
          z_ = 0;
          bitField0_ = (bitField0_ & ~0x00000004);
          type_ = "";
          bitField0_ = (bitField0_ & ~0x00000008);
          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return ignfab.minetest.MapProto.internal_static_Map_Block_descriptor;
        }

        public ignfab.minetest.MapProto.Map.Block getDefaultInstanceForType() {
          return ignfab.minetest.MapProto.Map.Block.getDefaultInstance();
        }

        public ignfab.minetest.MapProto.Map.Block build() {
          ignfab.minetest.MapProto.Map.Block result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public ignfab.minetest.MapProto.Map.Block buildPartial() {
          ignfab.minetest.MapProto.Map.Block result = new ignfab.minetest.MapProto.Map.Block(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.x_ = x_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.y_ = y_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.z_ = z_;
          if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
            to_bitField0_ |= 0x00000008;
          }
          result.type_ = type_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof ignfab.minetest.MapProto.Map.Block) {
            return mergeFrom((ignfab.minetest.MapProto.Map.Block)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(ignfab.minetest.MapProto.Map.Block other) {
          if (other == ignfab.minetest.MapProto.Map.Block.getDefaultInstance()) return this;
          if (other.hasX()) {
            setX(other.getX());
          }
          if (other.hasY()) {
            setY(other.getY());
          }
          if (other.hasZ()) {
            setZ(other.getZ());
          }
          if (other.hasType()) {
            bitField0_ |= 0x00000008;
            type_ = other.type_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          if (!hasX()) {
            return false;
          }
          if (!hasY()) {
            return false;
          }
          if (!hasZ()) {
            return false;
          }
          if (!hasType()) {
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          ignfab.minetest.MapProto.Map.Block parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (ignfab.minetest.MapProto.Map.Block) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private int x_ ;
        /**
         * <code>required int32 x = 1;</code>
         */
        public boolean hasX() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required int32 x = 1;</code>
         */
        public int getX() {
          return x_;
        }
        /**
         * <code>required int32 x = 1;</code>
         */
        public Builder setX(int value) {
          bitField0_ |= 0x00000001;
          x_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 x = 1;</code>
         */
        public Builder clearX() {
          bitField0_ = (bitField0_ & ~0x00000001);
          x_ = 0;
          onChanged();
          return this;
        }

        private int y_ ;
        /**
         * <code>required int32 y = 2;</code>
         */
        public boolean hasY() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required int32 y = 2;</code>
         */
        public int getY() {
          return y_;
        }
        /**
         * <code>required int32 y = 2;</code>
         */
        public Builder setY(int value) {
          bitField0_ |= 0x00000002;
          y_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 y = 2;</code>
         */
        public Builder clearY() {
          bitField0_ = (bitField0_ & ~0x00000002);
          y_ = 0;
          onChanged();
          return this;
        }

        private int z_ ;
        /**
         * <code>required int32 z = 3;</code>
         */
        public boolean hasZ() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>required int32 z = 3;</code>
         */
        public int getZ() {
          return z_;
        }
        /**
         * <code>required int32 z = 3;</code>
         */
        public Builder setZ(int value) {
          bitField0_ |= 0x00000004;
          z_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 z = 3;</code>
         */
        public Builder clearZ() {
          bitField0_ = (bitField0_ & ~0x00000004);
          z_ = 0;
          onChanged();
          return this;
        }

        private java.lang.Object type_ = "";
        /**
         * <code>required string type = 4;</code>
         */
        public boolean hasType() {
          return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        /**
         * <code>required string type = 4;</code>
         */
        public java.lang.String getType() {
          java.lang.Object ref = type_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              type_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string type = 4;</code>
         */
        public com.google.protobuf.ByteString
            getTypeBytes() {
          java.lang.Object ref = type_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            type_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string type = 4;</code>
         */
        public Builder setType(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
          type_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string type = 4;</code>
         */
        public Builder clearType() {
          bitField0_ = (bitField0_ & ~0x00000008);
          type_ = getDefaultInstance().getType();
          onChanged();
          return this;
        }
        /**
         * <code>required string type = 4;</code>
         */
        public Builder setTypeBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
          type_ = value;
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:Map.Block)
      }

      // @@protoc_insertion_point(class_scope:Map.Block)
      private static final ignfab.minetest.MapProto.Map.Block DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new ignfab.minetest.MapProto.Map.Block();
      }

      public static ignfab.minetest.MapProto.Map.Block getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @java.lang.Deprecated public static final com.google.protobuf.Parser<Block>
          PARSER = new com.google.protobuf.AbstractParser<Block>() {
        public Block parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Block(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Block> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Block> getParserForType() {
        return PARSER;
      }

      public ignfab.minetest.MapProto.Map.Block getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int CHUNK_BLOCKS_FIELD_NUMBER = 1;
    private int chunkBlocks_;
    /**
     * <code>required int32 chunk_blocks = 1;</code>
     */
    public boolean hasChunkBlocks() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 chunk_blocks = 1;</code>
     */
    public int getChunkBlocks() {
      return chunkBlocks_;
    }

    public static final int BLOCKS_FIELD_NUMBER = 2;
    private java.util.List<ignfab.minetest.MapProto.Map.Block> blocks_;
    /**
     * <code>repeated .Map.Block blocks = 2;</code>
     */
    public java.util.List<ignfab.minetest.MapProto.Map.Block> getBlocksList() {
      return blocks_;
    }
    /**
     * <code>repeated .Map.Block blocks = 2;</code>
     */
    public java.util.List<? extends ignfab.minetest.MapProto.Map.BlockOrBuilder> 
        getBlocksOrBuilderList() {
      return blocks_;
    }
    /**
     * <code>repeated .Map.Block blocks = 2;</code>
     */
    public int getBlocksCount() {
      return blocks_.size();
    }
    /**
     * <code>repeated .Map.Block blocks = 2;</code>
     */
    public ignfab.minetest.MapProto.Map.Block getBlocks(int index) {
      return blocks_.get(index);
    }
    /**
     * <code>repeated .Map.Block blocks = 2;</code>
     */
    public ignfab.minetest.MapProto.Map.BlockOrBuilder getBlocksOrBuilder(
        int index) {
      return blocks_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasChunkBlocks()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getBlocksCount(); i++) {
        if (!getBlocks(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, chunkBlocks_);
      }
      for (int i = 0; i < blocks_.size(); i++) {
        output.writeMessage(2, blocks_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, chunkBlocks_);
      }
      for (int i = 0; i < blocks_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, blocks_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ignfab.minetest.MapProto.Map)) {
        return super.equals(obj);
      }
      ignfab.minetest.MapProto.Map other = (ignfab.minetest.MapProto.Map) obj;

      boolean result = true;
      result = result && (hasChunkBlocks() == other.hasChunkBlocks());
      if (hasChunkBlocks()) {
        result = result && (getChunkBlocks()
            == other.getChunkBlocks());
      }
      result = result && getBlocksList()
          .equals(other.getBlocksList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasChunkBlocks()) {
        hash = (37 * hash) + CHUNK_BLOCKS_FIELD_NUMBER;
        hash = (53 * hash) + getChunkBlocks();
      }
      if (getBlocksCount() > 0) {
        hash = (37 * hash) + BLOCKS_FIELD_NUMBER;
        hash = (53 * hash) + getBlocksList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ignfab.minetest.MapProto.Map parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ignfab.minetest.MapProto.Map parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ignfab.minetest.MapProto.Map parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ignfab.minetest.MapProto.Map parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ignfab.minetest.MapProto.Map parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ignfab.minetest.MapProto.Map parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ignfab.minetest.MapProto.Map parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ignfab.minetest.MapProto.Map parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ignfab.minetest.MapProto.Map parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ignfab.minetest.MapProto.Map parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ignfab.minetest.MapProto.Map parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ignfab.minetest.MapProto.Map parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ignfab.minetest.MapProto.Map prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Map}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Map)
        ignfab.minetest.MapProto.MapOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ignfab.minetest.MapProto.internal_static_Map_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ignfab.minetest.MapProto.internal_static_Map_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ignfab.minetest.MapProto.Map.class, ignfab.minetest.MapProto.Map.Builder.class);
      }

      // Construct using ignfab.minetest.MapProto.Map.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getBlocksFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        chunkBlocks_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (blocksBuilder_ == null) {
          blocks_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          blocksBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ignfab.minetest.MapProto.internal_static_Map_descriptor;
      }

      public ignfab.minetest.MapProto.Map getDefaultInstanceForType() {
        return ignfab.minetest.MapProto.Map.getDefaultInstance();
      }

      public ignfab.minetest.MapProto.Map build() {
        ignfab.minetest.MapProto.Map result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ignfab.minetest.MapProto.Map buildPartial() {
        ignfab.minetest.MapProto.Map result = new ignfab.minetest.MapProto.Map(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.chunkBlocks_ = chunkBlocks_;
        if (blocksBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            blocks_ = java.util.Collections.unmodifiableList(blocks_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.blocks_ = blocks_;
        } else {
          result.blocks_ = blocksBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ignfab.minetest.MapProto.Map) {
          return mergeFrom((ignfab.minetest.MapProto.Map)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ignfab.minetest.MapProto.Map other) {
        if (other == ignfab.minetest.MapProto.Map.getDefaultInstance()) return this;
        if (other.hasChunkBlocks()) {
          setChunkBlocks(other.getChunkBlocks());
        }
        if (blocksBuilder_ == null) {
          if (!other.blocks_.isEmpty()) {
            if (blocks_.isEmpty()) {
              blocks_ = other.blocks_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureBlocksIsMutable();
              blocks_.addAll(other.blocks_);
            }
            onChanged();
          }
        } else {
          if (!other.blocks_.isEmpty()) {
            if (blocksBuilder_.isEmpty()) {
              blocksBuilder_.dispose();
              blocksBuilder_ = null;
              blocks_ = other.blocks_;
              bitField0_ = (bitField0_ & ~0x00000002);
              blocksBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getBlocksFieldBuilder() : null;
            } else {
              blocksBuilder_.addAllMessages(other.blocks_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasChunkBlocks()) {
          return false;
        }
        for (int i = 0; i < getBlocksCount(); i++) {
          if (!getBlocks(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ignfab.minetest.MapProto.Map parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ignfab.minetest.MapProto.Map) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int chunkBlocks_ ;
      /**
       * <code>required int32 chunk_blocks = 1;</code>
       */
      public boolean hasChunkBlocks() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 chunk_blocks = 1;</code>
       */
      public int getChunkBlocks() {
        return chunkBlocks_;
      }
      /**
       * <code>required int32 chunk_blocks = 1;</code>
       */
      public Builder setChunkBlocks(int value) {
        bitField0_ |= 0x00000001;
        chunkBlocks_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 chunk_blocks = 1;</code>
       */
      public Builder clearChunkBlocks() {
        bitField0_ = (bitField0_ & ~0x00000001);
        chunkBlocks_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<ignfab.minetest.MapProto.Map.Block> blocks_ =
        java.util.Collections.emptyList();
      private void ensureBlocksIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          blocks_ = new java.util.ArrayList<ignfab.minetest.MapProto.Map.Block>(blocks_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          ignfab.minetest.MapProto.Map.Block, ignfab.minetest.MapProto.Map.Block.Builder, ignfab.minetest.MapProto.Map.BlockOrBuilder> blocksBuilder_;

      /**
       * <code>repeated .Map.Block blocks = 2;</code>
       */
      public java.util.List<ignfab.minetest.MapProto.Map.Block> getBlocksList() {
        if (blocksBuilder_ == null) {
          return java.util.Collections.unmodifiableList(blocks_);
        } else {
          return blocksBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Map.Block blocks = 2;</code>
       */
      public int getBlocksCount() {
        if (blocksBuilder_ == null) {
          return blocks_.size();
        } else {
          return blocksBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Map.Block blocks = 2;</code>
       */
      public ignfab.minetest.MapProto.Map.Block getBlocks(int index) {
        if (blocksBuilder_ == null) {
          return blocks_.get(index);
        } else {
          return blocksBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Map.Block blocks = 2;</code>
       */
      public Builder setBlocks(
          int index, ignfab.minetest.MapProto.Map.Block value) {
        if (blocksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBlocksIsMutable();
          blocks_.set(index, value);
          onChanged();
        } else {
          blocksBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Map.Block blocks = 2;</code>
       */
      public Builder setBlocks(
          int index, ignfab.minetest.MapProto.Map.Block.Builder builderForValue) {
        if (blocksBuilder_ == null) {
          ensureBlocksIsMutable();
          blocks_.set(index, builderForValue.build());
          onChanged();
        } else {
          blocksBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Map.Block blocks = 2;</code>
       */
      public Builder addBlocks(ignfab.minetest.MapProto.Map.Block value) {
        if (blocksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBlocksIsMutable();
          blocks_.add(value);
          onChanged();
        } else {
          blocksBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Map.Block blocks = 2;</code>
       */
      public Builder addBlocks(
          int index, ignfab.minetest.MapProto.Map.Block value) {
        if (blocksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBlocksIsMutable();
          blocks_.add(index, value);
          onChanged();
        } else {
          blocksBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Map.Block blocks = 2;</code>
       */
      public Builder addBlocks(
          ignfab.minetest.MapProto.Map.Block.Builder builderForValue) {
        if (blocksBuilder_ == null) {
          ensureBlocksIsMutable();
          blocks_.add(builderForValue.build());
          onChanged();
        } else {
          blocksBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Map.Block blocks = 2;</code>
       */
      public Builder addBlocks(
          int index, ignfab.minetest.MapProto.Map.Block.Builder builderForValue) {
        if (blocksBuilder_ == null) {
          ensureBlocksIsMutable();
          blocks_.add(index, builderForValue.build());
          onChanged();
        } else {
          blocksBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Map.Block blocks = 2;</code>
       */
      public Builder addAllBlocks(
          java.lang.Iterable<? extends ignfab.minetest.MapProto.Map.Block> values) {
        if (blocksBuilder_ == null) {
          ensureBlocksIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, blocks_);
          onChanged();
        } else {
          blocksBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Map.Block blocks = 2;</code>
       */
      public Builder clearBlocks() {
        if (blocksBuilder_ == null) {
          blocks_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          blocksBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Map.Block blocks = 2;</code>
       */
      public Builder removeBlocks(int index) {
        if (blocksBuilder_ == null) {
          ensureBlocksIsMutable();
          blocks_.remove(index);
          onChanged();
        } else {
          blocksBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Map.Block blocks = 2;</code>
       */
      public ignfab.minetest.MapProto.Map.Block.Builder getBlocksBuilder(
          int index) {
        return getBlocksFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Map.Block blocks = 2;</code>
       */
      public ignfab.minetest.MapProto.Map.BlockOrBuilder getBlocksOrBuilder(
          int index) {
        if (blocksBuilder_ == null) {
          return blocks_.get(index);  } else {
          return blocksBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Map.Block blocks = 2;</code>
       */
      public java.util.List<? extends ignfab.minetest.MapProto.Map.BlockOrBuilder> 
           getBlocksOrBuilderList() {
        if (blocksBuilder_ != null) {
          return blocksBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(blocks_);
        }
      }
      /**
       * <code>repeated .Map.Block blocks = 2;</code>
       */
      public ignfab.minetest.MapProto.Map.Block.Builder addBlocksBuilder() {
        return getBlocksFieldBuilder().addBuilder(
            ignfab.minetest.MapProto.Map.Block.getDefaultInstance());
      }
      /**
       * <code>repeated .Map.Block blocks = 2;</code>
       */
      public ignfab.minetest.MapProto.Map.Block.Builder addBlocksBuilder(
          int index) {
        return getBlocksFieldBuilder().addBuilder(
            index, ignfab.minetest.MapProto.Map.Block.getDefaultInstance());
      }
      /**
       * <code>repeated .Map.Block blocks = 2;</code>
       */
      public java.util.List<ignfab.minetest.MapProto.Map.Block.Builder> 
           getBlocksBuilderList() {
        return getBlocksFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          ignfab.minetest.MapProto.Map.Block, ignfab.minetest.MapProto.Map.Block.Builder, ignfab.minetest.MapProto.Map.BlockOrBuilder> 
          getBlocksFieldBuilder() {
        if (blocksBuilder_ == null) {
          blocksBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              ignfab.minetest.MapProto.Map.Block, ignfab.minetest.MapProto.Map.Block.Builder, ignfab.minetest.MapProto.Map.BlockOrBuilder>(
                  blocks_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          blocks_ = null;
        }
        return blocksBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Map)
    }

    // @@protoc_insertion_point(class_scope:Map)
    private static final ignfab.minetest.MapProto.Map DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ignfab.minetest.MapProto.Map();
    }

    public static ignfab.minetest.MapProto.Map getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Map>
        PARSER = new com.google.protobuf.AbstractParser<Map>() {
      public Map parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Map(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Map> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Map> getParserForType() {
      return PARSER;
    }

    public ignfab.minetest.MapProto.Map getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MapInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MapInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string package_name = 1;</code>
     */
    boolean hasPackageName();
    /**
     * <code>required string package_name = 1;</code>
     */
    java.lang.String getPackageName();
    /**
     * <code>required string package_name = 1;</code>
     */
    com.google.protobuf.ByteString
        getPackageNameBytes();

    /**
     * <code>required int32 total_blocks = 2;</code>
     */
    boolean hasTotalBlocks();
    /**
     * <code>required int32 total_blocks = 2;</code>
     */
    int getTotalBlocks();
  }
  /**
   * Protobuf type {@code MapInfo}
   */
  public  static final class MapInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MapInfo)
      MapInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MapInfo.newBuilder() to construct.
    private MapInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MapInfo() {
      packageName_ = "";
      totalBlocks_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MapInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              packageName_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              totalBlocks_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ignfab.minetest.MapProto.internal_static_MapInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ignfab.minetest.MapProto.internal_static_MapInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ignfab.minetest.MapProto.MapInfo.class, ignfab.minetest.MapProto.MapInfo.Builder.class);
    }

    private int bitField0_;
    public static final int PACKAGE_NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object packageName_;
    /**
     * <code>required string package_name = 1;</code>
     */
    public boolean hasPackageName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string package_name = 1;</code>
     */
    public java.lang.String getPackageName() {
      java.lang.Object ref = packageName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          packageName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string package_name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPackageNameBytes() {
      java.lang.Object ref = packageName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        packageName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOTAL_BLOCKS_FIELD_NUMBER = 2;
    private int totalBlocks_;
    /**
     * <code>required int32 total_blocks = 2;</code>
     */
    public boolean hasTotalBlocks() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 total_blocks = 2;</code>
     */
    public int getTotalBlocks() {
      return totalBlocks_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasPackageName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTotalBlocks()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, packageName_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, totalBlocks_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, packageName_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, totalBlocks_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ignfab.minetest.MapProto.MapInfo)) {
        return super.equals(obj);
      }
      ignfab.minetest.MapProto.MapInfo other = (ignfab.minetest.MapProto.MapInfo) obj;

      boolean result = true;
      result = result && (hasPackageName() == other.hasPackageName());
      if (hasPackageName()) {
        result = result && getPackageName()
            .equals(other.getPackageName());
      }
      result = result && (hasTotalBlocks() == other.hasTotalBlocks());
      if (hasTotalBlocks()) {
        result = result && (getTotalBlocks()
            == other.getTotalBlocks());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasPackageName()) {
        hash = (37 * hash) + PACKAGE_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getPackageName().hashCode();
      }
      if (hasTotalBlocks()) {
        hash = (37 * hash) + TOTAL_BLOCKS_FIELD_NUMBER;
        hash = (53 * hash) + getTotalBlocks();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ignfab.minetest.MapProto.MapInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ignfab.minetest.MapProto.MapInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ignfab.minetest.MapProto.MapInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ignfab.minetest.MapProto.MapInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ignfab.minetest.MapProto.MapInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ignfab.minetest.MapProto.MapInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ignfab.minetest.MapProto.MapInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ignfab.minetest.MapProto.MapInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ignfab.minetest.MapProto.MapInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ignfab.minetest.MapProto.MapInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ignfab.minetest.MapProto.MapInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ignfab.minetest.MapProto.MapInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ignfab.minetest.MapProto.MapInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MapInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MapInfo)
        ignfab.minetest.MapProto.MapInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ignfab.minetest.MapProto.internal_static_MapInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ignfab.minetest.MapProto.internal_static_MapInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ignfab.minetest.MapProto.MapInfo.class, ignfab.minetest.MapProto.MapInfo.Builder.class);
      }

      // Construct using ignfab.minetest.MapProto.MapInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        packageName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        totalBlocks_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ignfab.minetest.MapProto.internal_static_MapInfo_descriptor;
      }

      public ignfab.minetest.MapProto.MapInfo getDefaultInstanceForType() {
        return ignfab.minetest.MapProto.MapInfo.getDefaultInstance();
      }

      public ignfab.minetest.MapProto.MapInfo build() {
        ignfab.minetest.MapProto.MapInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ignfab.minetest.MapProto.MapInfo buildPartial() {
        ignfab.minetest.MapProto.MapInfo result = new ignfab.minetest.MapProto.MapInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.packageName_ = packageName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.totalBlocks_ = totalBlocks_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ignfab.minetest.MapProto.MapInfo) {
          return mergeFrom((ignfab.minetest.MapProto.MapInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ignfab.minetest.MapProto.MapInfo other) {
        if (other == ignfab.minetest.MapProto.MapInfo.getDefaultInstance()) return this;
        if (other.hasPackageName()) {
          bitField0_ |= 0x00000001;
          packageName_ = other.packageName_;
          onChanged();
        }
        if (other.hasTotalBlocks()) {
          setTotalBlocks(other.getTotalBlocks());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPackageName()) {
          return false;
        }
        if (!hasTotalBlocks()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ignfab.minetest.MapProto.MapInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ignfab.minetest.MapProto.MapInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object packageName_ = "";
      /**
       * <code>required string package_name = 1;</code>
       */
      public boolean hasPackageName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string package_name = 1;</code>
       */
      public java.lang.String getPackageName() {
        java.lang.Object ref = packageName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            packageName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string package_name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getPackageNameBytes() {
        java.lang.Object ref = packageName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          packageName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string package_name = 1;</code>
       */
      public Builder setPackageName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        packageName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string package_name = 1;</code>
       */
      public Builder clearPackageName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        packageName_ = getDefaultInstance().getPackageName();
        onChanged();
        return this;
      }
      /**
       * <code>required string package_name = 1;</code>
       */
      public Builder setPackageNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        packageName_ = value;
        onChanged();
        return this;
      }

      private int totalBlocks_ ;
      /**
       * <code>required int32 total_blocks = 2;</code>
       */
      public boolean hasTotalBlocks() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 total_blocks = 2;</code>
       */
      public int getTotalBlocks() {
        return totalBlocks_;
      }
      /**
       * <code>required int32 total_blocks = 2;</code>
       */
      public Builder setTotalBlocks(int value) {
        bitField0_ |= 0x00000002;
        totalBlocks_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 total_blocks = 2;</code>
       */
      public Builder clearTotalBlocks() {
        bitField0_ = (bitField0_ & ~0x00000002);
        totalBlocks_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MapInfo)
    }

    // @@protoc_insertion_point(class_scope:MapInfo)
    private static final ignfab.minetest.MapProto.MapInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ignfab.minetest.MapProto.MapInfo();
    }

    public static ignfab.minetest.MapProto.MapInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<MapInfo>
        PARSER = new com.google.protobuf.AbstractParser<MapInfo>() {
      public MapInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MapInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MapInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MapInfo> getParserForType() {
      return PARSER;
    }

    public ignfab.minetest.MapProto.MapInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Map_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Map_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Map_Block_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Map_Block_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MapInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MapInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017map_proto.proto\"o\n\003Map\022\024\n\014chunk_blocks" +
      "\030\001 \002(\005\022\032\n\006blocks\030\002 \003(\0132\n.Map.Block\0326\n\005Bl" +
      "ock\022\t\n\001x\030\001 \002(\005\022\t\n\001y\030\002 \002(\005\022\t\n\001z\030\003 \002(\005\022\014\n\004" +
      "type\030\004 \002(\t\"5\n\007MapInfo\022\024\n\014package_name\030\001 " +
      "\002(\t\022\024\n\014total_blocks\030\002 \002(\005B\033\n\017ignfab.mine" +
      "testB\010MapProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Map_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Map_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Map_descriptor,
        new java.lang.String[] { "ChunkBlocks", "Blocks", });
    internal_static_Map_Block_descriptor =
      internal_static_Map_descriptor.getNestedTypes().get(0);
    internal_static_Map_Block_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Map_Block_descriptor,
        new java.lang.String[] { "X", "Y", "Z", "Type", });
    internal_static_MapInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_MapInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MapInfo_descriptor,
        new java.lang.String[] { "PackageName", "TotalBlocks", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
